version: "3.9"
services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: renthub
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    volumes:
      - redis-data:/data

  app:
    build:
      context: .
      dockerfile: cmd/app/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      - PORT=8080
      - DB=host=db user=postgres password=postgres dbname=renthub port=5432 sslmode=disable TimeZone=Asia/Tehran
      - RedisServer=redis:6379
      - RedisPass=

  broker:
    build:
      context: .
      dockerfile: cmd/broker/Dockerfile
    depends_on:
      - db
      - redis
    environment:
      - PORT=8080
      - DB=host=db user=postgres password=postgres dbname=renthub port=5432 sslmode=disable TimeZone=Asia/Tehran
      - RedisServer=redis:6379
      - RedisPass=

volumes:
  db-data:
  redis-data:
